# Generated by Django 3.2.5 on 2021-12-12 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.FloatField()),
                ('Imagen', models.ImageField(null=True, upload_to='articulos')),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Franquicia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Franquicia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoxArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInventarios.articulo')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPedido', models.DateField()),
                ('PrecioTotal', models.FloatField()),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PedidoxArticulo', models.ManyToManyField(to='GestionInventarios.PedidoxArticulo')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='Categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInventarios.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='Franquicia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionInventarios.franquicia'),
        ),
    ]
