# Generated by Django 3.2.5 on 2021-12-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pago', models.FloatField()),
                ('Estado', models.CharField(max_length=10)),
                ('carrito', models.IntegerField()),
            ],
        ),
    ]
