# Generated by Django 3.2.5 on 2021-12-12 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCompras', '0002_pago_iduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='FechaPago',
            field=models.DateField(default=datetime.datetime(2021, 12, 12, 23, 35, 24, 565807, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
