# Generated by Django 3.2.5 on 2021-12-12 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GestionCompras', '0003_pago_fechapago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(max_length=10)),
                ('FechaEntrega', models.DateField()),
                ('IdUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idPago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionCompras.pago')),
            ],
        ),
    ]
