# Generated by Django 3.2.5 on 2021-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionCompras', '0004_envios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envios',
            name='FechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
